#define FONT_OFFSET 0x50
#define MEM_SIZE 0x1000
#define PROGRAM_START 0x200

#define DISPLAY_WIDTH 64
#define DISPLAY_HEIGHT 32

#define PIXELS_PER_ROW WINDOW_WIDTH / DISPLAY_WIDTH
#define PIXELS_PER_COL WINDOW_HEIGHT / DISPLAY_HEIGHT

#define QUIRKY false
